name: Build and Commit LaTeX PDF

on:
  push:
    paths:
      - '**.tex'
  pull_request:
    paths:
      - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-lang-polish \
            latexmk
            
      - name: Generate LaTeX macro with current date
        run: |
          echo "\\renewcommand{\\LastUpdateDate}{\\textnormal{`date -u +'%Y-%m-%d %H:%M UTC'`}}" > LastUpdateDate.tex
        
      - name: Compile PDF
        run: |
          mkdir -p output
          latexmk -pdf -interaction=nonstopmode -halt-on-error -output-directory=output LubianaPiosenki.tex

      - name: Commit generated PDF if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add output/LubianaPiosenki.pdf

          if ! git diff --cached --quiet; then
            timestamp=$(date -u +"%Y-%m-%d %H:%M UTC")
            git commit -m "Auto-generated PDF from LubianaPiosenki.tex ($timestamp)"
            git push
          else
            echo "PDF has not changed. Skipping commit."
          fi

      - name: Copy PDF to publish folder
        if: success()
        run: |
          mkdir -p public
          cp output/LubianaPiosenki.pdf public/

      - name: Generate index.html with PDF redirect and version
        run: |
          VERSION=$(date -u +%Y%m%d%H%M)
      
          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html lang="pl">
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="refresh" content="0; url=LubianaPiosenki.pdf?v=${VERSION}" />
            <title>Przekierowanie do śpiewnika</title>
          </head>
          <body>
            <p>Przekierowuję do PDF-a... <a href="LubianaPiosenki.pdf?v=${VERSION}">Kliknij tutaj, jeśli nie nastąpiło przekierowanie.</a></p>
          </body>
          </html>
          EOF
          
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages



